---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: docker-test
spec:
  domains:
    - k8s.arhuaho.com
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: docker-test
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-test
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: docker-test
    networking.gke.io/v1beta1.FrontendConfig: docker-test
    networking.gke.io/managed-certificates: docker-test
spec:
  defaultBackend:
    service:
      name: docker-test
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docker-test
spec:
  type: NodePort
  selector:
    app: docker-test
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
  labels:
    app: docker-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
        - name: docker-test
          imagePullPolicy: Always
          image: asia-east1-docker.pkg.dev/GOOGLE_PROJECT/docker-test/app:latest
